version: '3'
services:
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:8.12.0
    container_name: packetbeat
    network_mode: host
    volumes:
      - /usr/share/packetbeat/data
      - /usr/share/packetbeat/logs
    environment:
      - "BEAT_STRICT_PERMS=false"
      - "ES_HOST=elasticsearch"
      - "KIBANA_HOST=kibana:5601"
      - "KIBANA_USERNAME=your_kibana_username"
      - "KIBANA_PASSWORD=your_kibana_password"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch:9200"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    restart: always
